# shellcheck disable=SC2034,SC2148
# Default file for APPLICATION_NAME
APP_NAME="APPLICATION_NAME";
LIB_SERVICE_MANIFEST="LIB_SVC_FILE";
SYSTEMD_SERVICE_MANIFEST="SYSD_SVC_FILE";
SERVICE_ENABLE_SCRIPT="SVC_ENABLE";
SERVICE_DISABLE_SCRIPT="SVC_DISABLE";
SERVICE_START_SCRIPT="SVC_START";
SERVICE_STOP_SCRIPT="SVC_STOP";
SERVICE_STATUS_SCRIPT="SVC_STATUS";
SERVICE_NAME="SVC_NAME";
SERVICE_USER_NAME="SVC_USER_NAME";
JAR_FILE="APP_JAR_FILE";
JAVA_HEAP_DUMPS="DUMP_DIR";
JAVA_LOG="LOG_DIR";
SPRING_CONF_FILE="ETC_CONF_FILE";
SPRING_CONF_LOG4J="ETC_CONF_LOG";
