#!/bin/bash

set -eu

if [ ! "$EUID" -eq 0 ]; then
    echo "You must be root to run this script" >&2;
    exit 1;
fi

if [ -f "@OUTPUT_LIQUIBASECREDS_FILE@" ]; then
    echo "The file @OUTPUT_LIQUIBASECREDS_FILE@ exists.";
    read -rp " Do you wan't to overwrite it? y/n [n]: " overwrite
    if [ ${overwrite:-"n"} == "n" ]; then
        exit 0;
    fi
fi

echo "Welcome to set the liquibase credentials for @NAME@";
echo "Let's now setup database configuration and credentials"
read -rp "Enter the database server hostname/IP address [localhost]: " dbserver
dbserver=${dbserver:-"localhost"}

read -rp "Enter the database server TCP port [3306]: " dbport
dbport=${dbport:-3306}

read -rp "Enter the database name [@APP_NAME@]: " dbname
dbname=${dbname:-@APP_NAME@}

read -rp "Enter the database server username [@SERVICE_USER_NAME@]: " dbusername
dbusername=${dbusername:-@SERVICE_USER_NAME@}

DEFAULT_URL="jdbc:mysql://$dbserver:$dbport/$dbname?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true";
read -rp "Enter the database JDBC URL [$DEFAULT_URL]: " dburl
dburl=${dburl:-$DEFAULT_URL}

read -rsp "Enter the database server user password: " dbuserpassword
echo "";

read -rp "Enter the JDBC driver [com.mysql.cj.jdbc.Driver]: " dbdriver
dbdriver=${dbdriver:-"com.mysql.cj.jdbc.Driver"}

#read -rp "Enter the Hibernate dialect [org.hibernate.dialect.MySQL8Dialect]: " dbdialect
#dbdialect=${dbdialect:-"org.hibernate.dialect.MySQL8Dialect"}

{
    echo "# This file is autogenerated by $0 setup, free feel to edit"
    echo "dbusername=\"$dbusername\"";
    echo "dbuserpassword=\"$dbuserpassword\"" ;
    echo "dburl=\"$dburl\"";
    echo "dbdriver=\"$dbdriver\"";
    echo "dbdialect=\"$dbdialect\"";
} > "@OUTPUT_LIQUIBASECREDS_FILE@"
echo "Please edit @OUTPUT_LIQUIBASECREDS_FILE@ to change this values (if needed), and restart this script after."

echo "Database setup is now stored in @OUTPUT_LIQUIBASECREDS_FILE@";

chmod 600 "@OUTPUT_LIQUIBASECREDS_FILE@"
chown root:root "@OUTPUT_LIQUIBASECREDS_FILE@"
