# Don't forget to set https://github.com/USER/REPO/settings/actions >> Workflow permissions >> (*) Read and write
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
name: Publish releases on new tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare setup
        run: |
          sudo apt-get install -y --no-install-recommends jq man pandoc xmlstarlet \
          rpm rpmlint tar build-essential binutils lintian debhelper dh-make devscripts
      - name: Make RPM file
        run: ./make-rpm.bash
      - name: Make DEB file
        run: ./make-deb.bash
      - name: Extract version tag
        run: echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
      - name: Extract RPM file name
        run: echo "RPM_FILE=$(find "rpmbuild/RPMS" -type f -name "*.rpm")" >> $GITHUB_ENV
      - name: Extract DEB file name
        run: echo "DEB_FILE=$(find . -maxdepth 1 -type f -name "*.deb")" >> $GITHUB_ENV
      - name: Create release
        run: |
          curl --request POST -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H 'X-GitHub-Api-Version: 2022-11-28' --fail \
          --data '{"tag_name":"${{ env.VERSION }}","target_commitish":"master","name":"${{ env.VERSION }}","draft":true,"prerelease":false,"generate_release_notes":false}' \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -o new-release.json
      - name: Extract release URL reference
        run: echo "UPLOAD_URL=$(cat new-release.json | jq ".upload_url" -r | cut -d "{" -f 1)" >> $GITHUB_ENV
      - name: Push created RPM file to release
        run: |
          curl --request POST -H "Accept: application/vnd.github+json" -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "X-GitHub-Api-Version: 2022-11-28" --fail \
          -H "Content-Type: text/plain" \
          --data-binary "@${{ env.RPM_FILE }}" \
          ${{ env.UPLOAD_URL }}?name=linux-springboot-packager-${{ env.VERSION }}.rpm
      - name: Push created DEB file to release
        run: |
          curl --request POST -H "Accept: application/vnd.github+json" -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "X-GitHub-Api-Version: 2022-11-28" --fail \
          -H "Content-Type: text/plain" \
          --data-binary "@${{ env.DEB_FILE }}" \
          ${{ env.UPLOAD_URL }}?name=linux-springboot-packager-${{ env.VERSION }}.deb
  